import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.models import Finding, Severity
from src.scoring.risk import calculate_score, grade_for_score, severity_counts


def make_finding(sev):
    return Finding(category="test", title="t", severity=sev, description="d", recommendation="r")


def test_no_findings_perfect_score():
    assert calculate_score([]) == 100


def test_critical_deducts_25():
    score = calculate_score([make_finding(Severity.CRITICAL)])
    assert score == 75


def test_score_floors_at_zero():
    findings = [make_finding(Severity.CRITICAL) for _ in range(10)]
    assert calculate_score(findings) == 0


def test_info_findings_dont_affect_score():
    score = calculate_score([make_finding(Severity.INFO) for _ in range(5)])
    assert score == 100


def test_grade_boundaries():
    assert grade_for_score(95) == "A"
    assert grade_for_score(85) == "B"
    assert grade_for_score(75) == "C"
    assert grade_for_score(65) == "D"
    assert grade_for_score(40) == "F"


def test_severity_counts():
    findings = [make_finding(Severity.CRITICAL), make_finding(Severity.CRITICAL), make_finding(Severity.LOW)]
    counts = severity_counts(findings)
    assert counts["CRITICAL"] == 2
    assert counts["LOW"] == 1
    assert counts["HIGH"] == 0


def test_finding_id_autogenerated():
    f = make_finding(Severity.HIGH)
    assert f.finding_id.startswith("HIGH-")
